@PROSD.backend.net_HostAddress = http://localhost:5221

### Get weather forecast
GET {{PROSD.backend.net_HostAddress}}/weatherforecast
Accept: application/json

### Create job
POST {{PROSD.backend.net_HostAddress}}/jobs
Content-Type: application/json

{
  "title": "Test job",
  "description": "first test"
}

### Get job by id
GET {{PROSD.backend.net_HostAddress}}/jobs/1
Accept: application/json